- name: PCAP analysis pipeline (batch, sequential)
  hosts: analysis
  gather_facts: false

  roles:
    - initial

  tasks:
    - name: Process PCAPs sequentially
      include_tasks: process_one_pcap.yml
      loop: "{{ pcap_files.files }}"
      loop_control:
        loop_var: pcap_item