- name: PCAP analysis pipeline
  hosts: analysis
  gather_facts: false
  roles:
    - initial
    - zeek_run
    - suricata_run
    - python_asngeo
    - python_correlate
    - python_report_alerts
    - python_report_stats
    - report_final
    - cleanup